core/urls.py
from django.urls import path,include
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('auth/', include('social_django.urls', namespace="social")),
    path('comments/<int:pk>/',views.CommentView.as_view(),name='comment')
]

eats_easy_ordering_system/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import RedirectView
from rest_framework import routers
from django.conf.urls import url
from django.conf import settings
from core.views import UserViewSet,ProductViewSet,HRViewSet,OrderViewSet
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token
from lunch.views import get_product_detail
# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'products',ProductViewSet)
router.register(r'hr',HRViewSet)
router.register(r'orders',OrderViewSet)
urlpatterns = [
    path('', RedirectView.as_view(url='/lunch/order/create', permanent=True)),
    path('admin/', admin.site.urls),
    path('web/', include('core.urls')),
    path('lunch/', include('lunch.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('hr/', include('human_resource.urls')),
    path('supplier/',include('supplier.urls')),
    # Wire up our API using automatic URL routing.
    # Additionally, we include login URLs for the browsable API.
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path(r'api-token-auth/', obtain_jwt_token),
    path(r'api-token-refresh/', refresh_jwt_token),
    path('ajax/getproduct/', get_product_detail, name='get_product_detail'),
]

# For debug-toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns


from django.conf.urls.static import static




# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

supplier/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('create/', views.SupplierView.as_view(), name='supplier_create'),
    path('',views.SupplierDetailView.as_view(),name='supplier'),
    path('update/<int:pk>',views.SupplierUpdateView.as_view(), name='supplier_update'),
    path('createproduct/',views.CreateProductView.as_view(),name='addproduct'),
    path('updateproduct/<int:pk>',views.UpdateProductView.as_view(),name='editproduct'),
]

lunch/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.


class Order(models.Model):
    """Blueprint for Order object"""
    weekorder = models.ForeignKey('human_resource.OrderForWeek',on_delete=models.SET_NULL,null=True)
    name = models.CharField(max_length=255,default='')
    user = models.ForeignKey(User, on_delete=models.SET_NULL,null=True)
    total = models.DecimalField(max_digits=9,decimal_places=2,verbose_name='Total')

    ORDER_STATUS = (('new', 'New'),('received', 'Received'))
    status = models.CharField(max_length=10,choices=ORDER_STATUS,blank=True, verbose_name='Status',default='new')
    date = models.DateField(null=True)

    def get_absolute_url(self):
        return reverse('myorder-detail', args=[str(self.id)])


class OrderLine(models.Model):
    order = models.ForeignKey('Order',on_delete=models.SET_NULL,null=True)
    product = models.ForeignKey('core.Product',on_delete=models.SET_NULL,null=True)
    date = models.DateField(verbose_name="Date",null=True)
    day = models.CharField(max_length=10,default="",blank=True)

supplier/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class Supplier(models.Model):
    class Meta:
        permissions = (("can_access_supplier","Can access Supplier"),)
        default_permissions = ()



class ProductforWeek(models.Model):
    name = models.CharField(default='',max_length=64)
    supplier = models.ForeignKey('core.Supplier',on_delete=models.SET_NULL,null=True)
    date = models.DateField(verbose_name="Date For")
    products = models.ManyToManyField('core.Product',related_name="supplier_products")
    active = models.BooleanField('Active',default=False)

    def get_absolute_url(self):
        return reverse('supplier')

supplier/forms.py
from django import forms


class SupplierForm(forms.Form):
    pass

supplier/views.py
from django.forms import CheckboxSelectMultiple, ModelForm
from django.shortcuts import render
from django.urls import reverse

from .models import ProductforWeek
from core.models import Product, Supplier
# Create your views here.
from django.views.generic import CreateView, UpdateView, DetailView, TemplateView, DeleteView


def index(request):
    return render(request, 'supplier_base_template.html')


class SupplierView(CreateView):
    template_name = "supplier/supplier_form.html"
    model = ProductforWeek
    fields = ('products','date')
    def get_context_data(self, **kwargs):
        supplier = Supplier.objects.filter(user=self.request.user)
        data = super(SupplierView, self).get_context_data(**kwargs)
        print(supplier[0].id)
        data['products'] = Product.objects.filter(supplier=supplier[0].id)
        print(data['products'])
        return data


class SupplierUpdateView(UpdateView):
    template_name ="supplier/supplier_update_form.html"
    model = ProductforWeek
    fields = ('products',)

    def get_context_data(self, **kwargs):
        supplier = Supplier.objects.filter(user=self.request.user)
        data = super(SupplierUpdateView,self).get_context_data(**kwargs)
        data['supply'] = ProductforWeek.objects.filter(active=True)
        data['products'] = Product.objects.filter(supplier=supplier[0].id).filter(active=True)
        selected = ProductforWeek.objects.prefetch_related("products").filter(active=True)
        sp = []
        for p in selected[0].products.all():
            sp.append(p.id)
        data["sp"] = sp

        return data
    def get_absolute_url(self):
        return reverse('supplier')


class SupplierDetailView(TemplateView):
    template_name ="supplier/supplier_form_detail.html"
    
    def get_context_data(self, *args, **kwargs):
        context = super(SupplierDetailView, self).get_context_data(*args, **kwargs)
        data = ProductforWeek.objects.filter(active=True)
        context['data'] = data[0]
        print(data[0])
        return context

class CreateProductForm(ModelForm):
    class Meta:
        model = Product
        exclude = ('supplier',)


class CreateProductView(CreateView):
    model = Product
    template_name = 'supplier/supplier_product_form.html'
    form_class = CreateProductForm
    success_url = '/supplier'

    def form_valid(self, form):
        supplier = Supplier.objects.filter(user=self.request.user)
        form.instance.supplier = supplier[0]
        form.instance.save()
        return super(CreateProductView, self).form_valid(form)

class UpdateProductView(UpdateView):
    model = Product
    form_class = CreateProductForm
    success_url = '/supplier'
    template_name = 'supplier/supplier_product_update_form.html'

supplier/templates/supplier/supplier_form.html
{% extends "supplier_base_template.html" %}
{% block extrahead %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/order.css' %}">
{% endblock extrahead %}


{% block action %}
<div class="col-sm-9">
    <form method="post">
        {% csrf_token %}
        <br>
        <input type="submit" value="Save" class="default" name="_save">
        <hr>
        <div class="row">
                {% for product in products %}
                <div class="column">
                    <div class="box">
                        <label>
                        <img id="mon_{{ product.id }}" src="{{ MEDIA_URL }} {{ product.image.url }}" style="width:100%">
                        <input type="radio" id="id_orderline_set-0-product_{{forloop.counter0}}" name="orderline_set-0-product" value="{{ food.id }}">
                        <h1 class="des">{{ product.name}} </h1>
                        </labeL>
                    </div>
                </div>
                {% endfor %}
                <input type="hidden" name="orderline_set-0-day" id="id_orderline_set-0-day" maxlength="10">
        </div>
    </form>
</div>

{% endblock action %}

supplier/templates/supplier/supplier_form_detail.html
{% extends "supplier_base_template.html" %}
{% block extrahead %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/order.css' %}">
{% endblock extrahead %}


{% block action %}
<div class="col-sm-9">
    <a href="{% url 'supplier_update' data.pk %}" class="btn btn-info" role="button">Update</a>
        <hr>
        <div class="row">
                {% for product in data.products.all %}
                <div class="column">
                    <div class="box">
                        <label>
                        <img id="mon_{{ product.id }}" src="{{ MEDIA_URL }} {{ product.image.url }}" style="width:100%">
                        <h1 class="des">{{ product.name}} </h1>
                        </labeL>
                    </div>
                </div>
                {% endfor %}
        </div>
</div>

{% endblock action %}

supplier/templates/supplier/supplier_product_form.html
{% extends "supplier_base_template.html" %}
{% block extrahead %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/order.css' %}">
{% endblock extrahead %}


{% block action %}
<div class="col-sm-9">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <br>
        <input type="submit" value="Save" class="default" name="_save">
        <hr>
        {{ form.as_p }}
    </form>
</div>

{% endblock action %}

supplier/templates/supplier/supplier_product_update_form.html
{% extends "supplier_base_template.html" %}
{% block extrahead %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/order.css' %}">
{% endblock extrahead %}


{% block action %}
<div class="col-sm-9">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <br>
        <input type="submit" value="Save" class="default" name="_save">
        <hr>
        {{ form.as_p }}
    </form>
</div>

{% endblock action %}

supplier/templates/supplier/supplier_update_form.html
{% extends "supplier_base_template.html" %}
{% block extrahead %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/order.css' %}">

{% endblock extrahead %}


{% block action %}
<div class="col-sm-9">
    <form method="post">
        {% csrf_token %}
        <br>
        <input type="submit" value="Save" class="default" name="_save">
        <hr>

               <!--<select multiple="multiple" name="products" id="id_products">-->
            <!--{% for cat in products %}-->
            <!--{% if cat.id in sp %}<option selected value="{{ cat.id }}">{{ cat }}</option> {% endif %}-->
            <!--{% endfor %}-->
        <!--</select>-->
<!--if sala in beer.salas_set.all():-->
    <!--#do stuff:-->
<!--else:-->
    <!--# do other stuff-->

        <div class="row">
                {% for product in products %}
                <div class="column">
                    <div class="box">
                        <label>
                        <img id="mon_{{ product.id }}" src="{{ MEDIA_URL }} {{ product.image.url }}" style="width:100%">
                        <input {% if product.id in sp %} checked {% endif %} type="checkbox" name="products" value="{{product.id}}">
                        <a href="{% url 'editproduct' product.id %}">Edit Product</a>
                            <h1 class="des">{{ product.name}} </h1>
                        </labeL>
                    </div>
                </div>
                {% endfor %}
        </div>
    </form>
</div>

{% endblock action %}