core/urls.py
from django.urls import path,include
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('auth/', include('social_django.urls', namespace="social")),
    path('comments/<int:pk>/',views.CommentView.as_view(),name='comment')
]

eats_easy_ordering_system/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import RedirectView
from rest_framework import routers
from django.conf.urls import url
from django.conf import settings
from core.views import UserViewSet,ProductViewSet,HRViewSet,OrderViewSet
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token
from lunch.views import get_product_detail
# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'products',ProductViewSet)
router.register(r'hr',HRViewSet)
router.register(r'orders',OrderViewSet)
urlpatterns = [
    path('', RedirectView.as_view(url='/lunch/order/create', permanent=True)),
    path('admin/', admin.site.urls),
    path('web/', include('core.urls')),
    path('lunch/', include('lunch.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('hr/', include('human_resource.urls')),
    path('supplier/',include('supplier.urls')),
    # Wire up our API using automatic URL routing.
    # Additionally, we include login URLs for the browsable API.
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path(r'api-token-auth/', obtain_jwt_token),
    path(r'api-token-refresh/', refresh_jwt_token),
    path('ajax/getproduct/', get_product_detail, name='get_product_detail'),
]

# For debug-toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns


from django.conf.urls.static import static




# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lunch/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
urlpatterns = [
    path('order/create/', views.CreateOrderView.as_view(), name='order-create'),
    path('order/<int:pk>/update/', views.OrderUpdateView.as_view(), name='order-update'),
    path('order/<int:pk>/', views.OrderDetailView.as_view(), name='myorder-detail'),
    path('orders/', views.OrdersOfUserListView.as_view(), name='my-orders'),

]

lunch/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.


class Order(models.Model):
    """Blueprint for Order object"""
    weekorder = models.ForeignKey('human_resource.OrderForWeek',on_delete=models.SET_NULL,null=True)
    name = models.CharField(max_length=255,default='')
    user = models.ForeignKey(User, on_delete=models.SET_NULL,null=True)
    total = models.DecimalField(max_digits=9,decimal_places=2,verbose_name='Total')

    ORDER_STATUS = (('new', 'New'),('received', 'Received'))
    status = models.CharField(max_length=10,choices=ORDER_STATUS,blank=True, verbose_name='Status',default='new')
    date = models.DateField(null=True)

    def get_absolute_url(self):
        return reverse('myorder-detail', args=[str(self.id)])


class OrderLine(models.Model):
    order = models.ForeignKey('Order',on_delete=models.SET_NULL,null=True)
    product = models.ForeignKey('core.Product',on_delete=models.SET_NULL,null=True)
    date = models.DateField(verbose_name="Date",null=True)
    day = models.CharField(max_length=10,default="",blank=True)

lunch/forms.py
from django import forms
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from .models import Order,OrderLine
from django.forms import inlineformset_factory,RadioSelect


class OrderLineForm(ModelForm):
    class Meta:
        model = OrderLine
        fields = ('product','day')
        widgets = {
            'product': RadioSelect(attrs={'cols': 80, 'rows': 20}),
        }

OrderLineFormSet = inlineformset_factory(Order,OrderLine,form=OrderLineForm, extra=5)





# class OrderForm(ModelForm):
#
#     class Meta:
#         model = Order
#         fields = ('total', 'status', 'date')
#
#     def __init__(self, *args, **kwargs):
#         super(OrderForm, self).__init__(*args,**kwargs)
#         self.fields['status'].widget.attrs['readonly'] = True
#

# class OrderForm(forms.Form):
#     """ TEST """
#     order_date = forms.DateField(help_text="Date of Order",required=True)
#
#     def clean_order_date(self):
#         data = self.cleaned_data['order_date']
#         if data < datetime.date.today():
#             raise ValidationError('Invalid date')
#
#         return data
#
#
# class OrderModelForm(ModelForm):
#     def clean_date(self):
#         data = self.cleaned_data['date']
#
#         return data
#
#     class Meta:
#         model = Order
#         fields = '__all__'

lunch/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import render, render_to_response, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.core import serializers

from .models import Order, OrderLine
from django.views.generic import DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from extra_views import CreateWithInlinesView, InlineFormSetFactory
from .forms import OrderLineFormSet
import datetime
from pprint import pprint
from human_resource.models import OrderForWeek
from django.http import JsonResponse, HttpResponseRedirect

from core.models import Product


# Create your views here.

def get_product_detail(request):
    pid = request.GET.get('id', None)
    obj = Product.objects.get(id=pid)
    data = {
        'product': serializers.serialize('json', [obj])
    }
    return JsonResponse(data)


class OrdersOfUserListView(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'lunch/orders_list_of_user.html'
    paginate_by = 50

    def get_queryset(self):
        return Order.objects.filter(user_id=self.request.user)


class OrderListView(ListView):
    model = Order
    paginate_by = 10


class OrderDetailView(DetailView):
    model = Order

    def get_context_data(self, **kwargs):
        context = super(OrderDetailView, self).get_context_data(**kwargs)
        # d = Order.orderline_set.objects.all()
        # d = OrderLine.objects.select_related('order').get(id=self.kwargs['pk'])
        order = Order.objects.get(id=self.kwargs['pk'])
        orderlines = order.orderline_set.all()
        print(orderlines[0].product)
        # y = x.p_perm
        context['orderlines'] = orderlines
        # print("!!!!!!!!!!!")
        # print(context['order'].weekorder_id.monday.name)
        # for x in context['order'].weekorder.values():
        #      print(x)
        return context


class OrderLineInline(InlineFormSetFactory):
    model = OrderLine
    fields = ['product', 'date', 'day']


class CreateOrderView(CreateView):
    model = Order
    fields = ('name',)
    template_name = 'lunch/order_form.html'
    success_message = "Order success"

    def get_success_url(self):
        return reverse('myorder-detail', args=(self.object.id,))

    def get_context_data(self, **kwargs):
        data = super(CreateOrderView, self).get_context_data(**kwargs)
        if self.request.POST:
            data['orderlines'] = OrderLineFormSet(self.request.POST)
        else:
            try:
                order = OrderForWeek.objects.filter(status='active').latest('date')
                check = Order.objects.filter(user=self.request.user, weekorder=order).count()
                data['check'] = check
                order = OrderForWeek.objects.filter(status='active').latest('date')
                data['order'] = order
                data['mondays'] = order.monday.all()
                data['tuesdays'] = order.tuesday.all()
                data['wednesdays'] = order.wednesday.all()
                data['thursdays'] = order.thursday.all()
                data['fridays'] = order.friday.all()
            except Exception as e:
                pass
            data['orderlines'] = OrderLineFormSet()
        return data

    def form_valid(self, form):
        total_price = 0
        order = OrderForWeek.objects.filter(status='active').latest('date')
        print("awefzxcvzxc")

        num = order.id
        form.instance.total = 0  # this is for initial data only
        form.instance.date = datetime.datetime.now()  # this is for initial data only
        context = self.get_context_data()
        orderlines = context['orderlines']
        # pprint(orderlines.data)
        # for key, val in orderlines.data.items():
        #     print(key, "==",val)
        #     if key:
        if orderlines.is_valid():
            for f in orderlines:
                cd = f.cleaned_data
                if cd:
                    # print(cd['day'])
                    total_price = total_price + cd['product'].price
            print("??????")
            self.object = form.save()
            orderlines.instance = self.object
            orderlines.save()
            # ORDER FORM
            print("!!!!!!!")
            form.instance.weekorder = order
            form.instance.user = self.request.user
            form.instance.total = total_price
            form.instance.save()
            return super(CreateOrderView, self).form_valid(form)
        else:
            print(orderlines.errors)
        return None


# class CreateOrderView(CreateWithInlinesView):
#     model = Order
#     fields = ('total','status','date')
#     inlines = [OrderLineInline]
#     template_name = 'lunch/order_form.html'
#
#     def forms_valid(self, form, inlines):
#         # TODO: order name
#         form.instance.user = self.request.user
#         form.instance.save()
#         return super(CreateOrderView, self).forms_valid(form,inlines)


class OrderUpdateView(UpdateView):
    model = Order
    fields = ('name',)
    template_name = 'lunch/order_update_form.html'
    queryset = Order.objects.all()

    def get_context_data(self, **kwargs):
        data = super(OrderUpdateView, self).get_context_data(**kwargs)
        # BooksFormSet = inlineformset_factory(Author, Book, fields='__all__', extra=1)
        if self.request.POST:
            # Create a formset instance to edit an existing model object,
            # but use POST data to populate the formset.
            # data['orderlines'] = OrderLineFormSet(self.request.POST)
            data['orderlines'] = OrderLineFormSet(self.request.POST, instance=self.get_object())
            print(data['orderlines'])

        else:
            # Create a formset with the data from model object and add it to context
            data['orderlines'] = OrderLineFormSet(instance=self.get_object())
            order = OrderForWeek.objects.filter(status='active').latest('date')
            check = Order.objects.filter(user=self.request.user, weekorder=order).count()
            cp = []
            for day in ['monday', 'tuesday', 'wednesday', 'thursday', 'friday']:
                orders = OrderLine.objects.select_related("order").filter(order__weekorder=order).filter(
                    order__user=self.request.user).filter(day=day).values_list('product_id', flat=True)
                cp.append(orders[0])
            data['cp'] = cp
            data['check'] = check
            data['order'] = order
            data['mondays'] = order.monday.all()
            data['tuesdays'] = order.tuesday.all()
            data['wednesdays'] = order.wednesday.all()
            data['thursdays'] = order.thursday.all()
            data['fridays'] = order.friday.all()

        return data


    def form_valid(self, form):
        total_price = 0
        order = OrderForWeek.objects.filter(status='active').latest('date')
        print("awefzxcvzxc")

        num = order.id
        form.instance.total = 0  # this is for initial data only
        form.instance.date = datetime.datetime.now()  # this is for initial data only
        context = self.get_context_data()
        orderlines = context['orderlines']
        # pprint(orderlines.data)
        # for key, val in orderlines.data.items():
        #     print(key, "==",val)
        #     if key:
        if orderlines.is_valid():
            for f in orderlines:
                cd = f.cleaned_data
                if cd:
                    # print(cd['day'])
                    total_price = total_price + cd['product'].price
            print("??????")
            self.object = form.save()
            orderlines.instance = self.object
            orderlines.save()
            # ORDER FORM
            print("!!!!!!!")
            form.instance.weekorder = order
            form.instance.user = self.request.user
            form.instance.total = total_price
            form.instance.save()
            return super(OrderUpdateView, self).form_valid(form)
        else:
            print(orderlines.errors)
        return None

    def get_object(self, queryset=None):
        id_ = self.kwargs.get("pk")
        return get_object_or_404(Order, id=id_)

    def get_success_url(self):
        return reverse('myorder-detail', args=(self.object.id,))


class OrderDelete(DeleteView):
    model = Order
    success_url = reverse_lazy('order')

lunch/templates/lunch/order_confirm_delete.html
{% extends "base_site.html" %}
{% load static %}

{% block content %}
    {% if user.is_authenticated %}
        <div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h5>Order now!</h5>
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="#section1">My Order</a></li>
      </ul><br>
    </div>

    <div class="col-sm-9">
        <form action="" method="post">
            {% csrf_token %}
            <input type="submit" value="Save" class="default">
            <table>
                {{ form.as_table }}
            </table>
        </form>
      <hr>
      <h2>I Love Food</h2>
      <label for="datepicker">Date:</label>
      <input id="datepicker" type="text" />
      <h5><span class="label label-danger">Food</span> <span class="label label-primary">Ipsum</span></h5><br>
      <p>Food is my passion. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
      <br><br>
    </div>
  </div>
</div>
<script src="{% static 'js/lunch.js' %}"></script>
    {% else %}
        <a href="{% url 'login' %}">Log in</a>
    {% endif %}
{% endblock content %}

lunch/templates/lunch/order_detail.html
{% extends "lunch_base_template.html" %}
{% block extrahead %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/odetail.css' %}">
{% endblock extrahead %}
{% block action %}

<div class="col-sm-9">
    <h4 class="detail-name">{{ order.name }}</h4>
    <h4 class="detail-status">Status: {{ order.status }}</h4>
    {% if order.weekorder.status == "active" %}<a href="{% url 'order-update' order.pk %}" class="btn btn-info" role="button">Update</a>{% endif %}

    <hr>
    <div class="day">
        <table id="customers">
            <tr>
                <th>Day</th>
                <th>Order</th>
            </tr>

            {% for order in orderlines %}
            <tr>
                <td>{{ order.day.title }}</td>
                <td>{{ order.product.name }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock action %}

lunch/templates/lunch/order_form.html
{% extends "lunch_base_template.html" %}

{% block extrahead %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/order.css' %}">
<style>
    /* HIDE RADIO */
[type=radio] {
  position: absolute;
  opacity: 0;
  width: 0;
  height: 0;
}

/* IMAGE STYLES */
[type=radio] + img {
  cursor: pointer;
}

/* CHECKED STYLES */
[type=radio]:checked + h1 {
  outline: 2px solid blue;
  color: blue;
}
</style>
{% endblock extrahead %}

{% block action %}


<div class="col-sm-9">
    {% if order %}
    {% if not check %}
    <form method="post">
        <h4 id="form_name" class="detail-name">{{ form.name.as_hidden }}</h4>
        <h4 class="detail-status">Status: NEW</h4>

        <h4 style="float: right;padding-right: 250px;">Order Info: {{ order.name }}</h4>
        {% csrf_token %}
        <br>
        <input type="submit" value="Save" class="default">
        <hr>
                 {{ orderlines.management_form }}
            <!--{% for orderline in orderlines.forms %}-->
            <!--{{ orderline.as_p }}-->
            <!--{% endfor %}-->

        <h2>Monday</h2>
        <div class="row">
            <fieldset id="mondaygroup">
                {% for food in mondays %}
                <div class="column">
                    <div class="box">
                        <label>
                        <img id="mon_{{ food.id }}" src="{{ MEDIA_URL }} {{ food.image.url }}" style="width:100%">
                        <input type="radio" id="id_orderline_set-0-product_{{forloop.counter0}}" name="orderline_set-0-product" value="{{ food.id }}">
                        <h1 class="des">{{ food.name}} </h1>
                        <a href="{% url 'comment' food.pk %}" onclick="return popitup('{% url 'comment' food.pk %}')">Comments</a>
                        </labeL>
                    </div>
                </div>
                {% endfor %}
                <input type="hidden" name="orderline_set-0-day" id="id_orderline_set-0-day" maxlength="10">
            </fieldset>
        </div>
        <h2>Tuesday</h2>
        <div class="row">
            <fieldset id="tuesdaygroup">
                {% for food in tuesdays %}
                <div class="column">
                    <div class="box">
                        <label>
                        <img id="tue_{{ food.id }}" src="{{ MEDIA_URL }} {{ food.image.url }}" style="width:100%">
                        <input type="radio" id="id_orderline_set-1-product_{{forloop.counter0}}" name="orderline_set-1-product" value="{{ food.id }}">
                        <h1 class="des">{{ food.name}} </h1>
                        <a href="{% url 'comment' food.pk %}" onclick="return popitup('{% url 'comment' food.pk %}')">Comments</a>
                        </label>
                    </div>
                </div>
                {% endfor %}
                <input type="hidden" name="orderline_set-1-day" id="id_orderline_set-1-day" maxlength="10">

            </fieldset>
        </div>
        <h2>Wednesday</h2>
        <div class="row">
            <fieldset id="wednesdaygroup">
                {% for food in wednesdays %}
                <div class="column">
                    <div class="box">
                        <label>
                        <img id="wed_{{ food.id }}" src="{{ MEDIA_URL }} {{ food.image.url }}" style="width:100%">
                        <input type="radio" id="id_orderline_set-2-product_{{forloop.counter0}}" name="orderline_set-2-product" value="{{ food.id }}">
                        <h1 class="des">{{ food.name}} </h1>
                        <a href="{% url 'comment' food.pk %}" onclick="return popitup('{% url 'comment' food.pk %}')">Comments</a>


                        </label>
                    </div>
                </div>
                {% endfor %}
                <input type="hidden" name="orderline_set-2-day" id="id_orderline_set-2-day" maxlength="10">

            </fieldset>
        </div>
        <h2>Thursday</h2>
        <div class="row">
            <fieldset id="thursdaygroup">

                {% for food in thursdays %}
                <div class="column">
                    <div class="box">
                        <label>
                        <img id="thu_{{ food.id }}" src="{{ MEDIA_URL }} {{ food.image.url }}" style="width:100%">
                        <input type="radio" id="id_orderline_set-3-product_{{forloop.counter0}}" name="orderline_set-3-product" value="{{ food.id }}">
                        <h1 class="des">{{ food.name}} </h1>
                        <a href="{% url 'comment' food.pk %}" onclick="return popitup('{% url 'comment' food.pk %}')">Comments</a>

                        </label>
                    </div>
                </div>
                {% endfor %}
                        <input type="hidden" name="orderline_set-3-day" id="id_orderline_set-3-day" maxlength="10">
            </fieldset>
        </div>

        <h2>Friday</h2>
        <div class="row">
            <fieldset id="fridaygroup">
                {% for food in fridays %}
                <div class="column">
                    <div class="box">
                        <label>
                        <img id="fri_{{ food.id }}" src="{{ MEDIA_URL }} {{ food.image.url }}" style="width:100%">
                        <input type="radio" id="id_orderline_set-4-product_{{forloop.counter0}}" name="orderline_set-4-product" value="{{ food.id }}">
                        <h1 class="des">{{ food.name}} </h1>
                        <a href="{% url 'comment' food.pk %}" onclick="return popitup('{% url 'comment' food.pk %}')">Comments</a>
                        </label>
                    </div>
                </div>
                {% endfor %}
                <input type="hidden" name="orderline_set-4-day" id="id_orderline_set-4-day" maxlength="10">
            </fieldset>
        </div>
    </form>
    {% else %}
    LOOKS LIKE YOU'VE ORDERED ALREADY
    {% endif %}
    {% else %}
    THERE'S NO ACTIVE ORDERS FROM HR
    {% endif %}
</div>

<script language="javascript" type="text/javascript">
<!--
function popitup(url) {
    newwindow=window.open(url,'{{title}}','height=500,width=600');
    if (window.focus) {
    newwindow.focus()
    }
    return false;
}

// -->
</script>


{% endblock action %}

lunch/templates/lunch/order_update_form.html
{% extends "lunch_base_template.html" %}

{% block extrahead %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/order.css' %}">
<style>
    /* HIDE RADIO */
[type=radio] {
  position: absolute;
  opacity: 0;
  width: 0;
  height: 0;
}

/* IMAGE STYLES */
[type=radio] + img {
  cursor: pointer;
}

/* CHECKED STYLES */
[type=radio]:checked + h1 {
  outline: 2px solid blue;
  color: blue;
}
</style>

{% endblock extrahead %}

{% block action %}


<div class="col-sm-9">
        {% if order %}

    <form method="post">
                <h4 id="form_name" class="detail-name">{{ form.name.as_hidden }}</h4>
        <h4 class="detail-status">Status: NEW</h4>

        <h4 style="float: right;padding-right: 250px;">Order Info: {{ order.name }}</h4>
        {% csrf_token %}
        <br>
        <input type="submit" value="Save" class="default">
        <hr>
                 {{ orderlines.management_form }}

        <h2>Monday</h2>
        <div class="row">
            <fieldset id="mondaygroup">
                {% for food in mondays %}
                <div class="column">
                    <div class="box">
                        <label>
                        <img id="mon_{{ food.id }}" src="{{ MEDIA_URL }} {{ food.image.url }}" style="width:100%">
                        <input {% if food.id in cp %} checked {% endif %} type="radio" id="id_orderline_set-0-product_{{forloop.counter0}}" name="orderline_set-0-product" value="{{ food.id }}">
                        <h1 class="des">{{ food.name}} </h1>
                        <a href="{% url 'comment' food.pk %}" onclick="return popitup('{% url 'comment' food.pk %}')">Comments</a>
                        </labeL>
                    </div>
                </div>
                {% endfor %}
                <input type="hidden" name="orderline_set-0-day" id="id_orderline_set-0-day" maxlength="10">
            </fieldset>
        </div>
        <h2>Tuesday</h2>
        <div class="row">
            <fieldset id="tuesdaygroup">
                {% for food in tuesdays %}
                <div class="column">
                    <div class="box">
                        <label>
                        <img id="tue_{{ food.id }}" src="{{ MEDIA_URL }} {{ food.image.url }}" style="width:100%">
                        <input {% if food.id in cp %} checked {% endif %} type="radio" id="id_orderline_set-1-product_{{forloop.counter0}}" name="orderline_set-1-product" value="{{ food.id }}">
                        <h1 class="des">{{ food.name}} </h1>
                        </label>
                    </div>
                </div>
                {% endfor %}
                <input type="hidden" name="orderline_set-1-day" id="id_orderline_set-1-day" maxlength="10">

            </fieldset>
        </div>
        <h2>Wednesday</h2>
        <div class="row">
            <fieldset id="wednesdaygroup">
                {% for food in wednesdays %}
                <div class="column">
                    <div class="box">
                        <label>
                        <img id="wed_{{ food.id }}" src="{{ MEDIA_URL }} {{ food.image.url }}" style="width:100%">
                        <input {% if food.id in cp %} checked {% endif %} type="radio" id="id_orderline_set-2-product_{{forloop.counter0}}" name="orderline_set-2-product" value="{{ food.id }}">
                        <h1 class="des">{{ food.name}} </h1>

                        </label>
                    </div>
                </div>
                {% endfor %}
                <input type="hidden" name="orderline_set-2-day" id="id_orderline_set-2-day" maxlength="10">

            </fieldset>
        </div>
        <h2>Thursday</h2>
        <div class="row">
            <fieldset id="thursdaygroup">

                {% for food in thursdays %}
                <div class="column">
                    <div class="box">
                        <label>
                        <img id="thu_{{ food.id }}" src="{{ MEDIA_URL }} {{ food.image.url }}" style="width:100%">
                        <input {% if food.id in cp %} checked {% endif %} type="radio" id="id_orderline_set-3-product_{{forloop.counter0}}" name="orderline_set-3-product" value="{{ food.id }}">
                        <h1 class="des">{{ food.name}} </h1>

                        </label>
                    </div>
                </div>
                {% endfor %}
                        <input {% if food.id in cp %} checked {% endif %} type="hidden" name="orderline_set-3-day" id="id_orderline_set-3-day" maxlength="10">
            </fieldset>
        </div>

        <h2>Friday</h2>
        <div class="row">
            <fieldset id="fridaygroup">
                {% for food in fridays %}
                <div class="column">
                    <div class="box">
                        <label>
                        <img id="fri_{{ food.id }}" src="{{ MEDIA_URL }} {{ food.image.url }}" style="width:100%">
                        <input {% if food.id in cp %} checked {% endif %} type="radio" id="id_orderline_set-4-product_{{forloop.counter0}}" name="orderline_set-4-product" value="{{ food.id }}">
                        <h1 class="des">{{ food.name}} </h1>
                        </label>
                    </div>
                </div>
                {% endfor %}
                <input type="hidden" name="orderline_set-4-day" id="id_orderline_set-4-day" maxlength="10">
            </fieldset>
        </div>
    </form>
    {% else %}
    YOUR ORDER WAS ALREADY ORDERED
    {% endif %}
</div>

{% endblock action %}

lunch/templates/lunch/orders_list_of_user.html
{% extends "lunch_base_template.html" %}

{% block action %}
<div class="col-sm-9">
    <h4>My Orders</h4>
    <hr style="margin-bottom: 0px;">
    <div class="results">
        <table id="result_list">
            <thead>
            <tr>
                <th scope="col" class="sortable column-name">
                    <div class="text">
                        <a>Name</a>
                    </div>
                    <div class="clear"></div>
                </th>
                <th scope="col" class="sortable column-date">
                    <div class="text">
                        <a>Date</a>
                    </div>
                    <div class="clear"></div>
                </th>
                <th scope="col" class="sortable column-total">
                    <div class="text">
                        <a>Total</a>
                    </div>
                    <div class="clear"></div>
                </th>
                <th scope="col" class="sortable column-supplier">
                    <div class="text">
                        <a>Order</a>
                    </div>
                    <div class="clear"></div>
                </th>
                <th scope="col" class="sortable column-status">
                    <div class="text">
                        <a>Status</a>
                    </div>
                    <div class="clear"></div>
                </th>
            </tr>
            </thead>
            <tbody>
            {% for order in order_list %}
            <tr class="{% cycle 'row1' 'row2' %}">
                <td class="field-name"><a href="{% url 'myorder-detail' order.pk %}">{{ order.name }}</a></td>
                <td class="field-date">{{ order.date }}</td>
                <td class="field-total">{{ order.total }}</td>
                <td class="field-supplier">{{ order.weekorder.name }}</td>
                <td class="field-status">{{ order.status }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock action %}